backend:
  name: github
  repo: wuwu/venohr # Change to your repo
  branch: master

media_folder: "static/uploads"
public_folder: uploads

collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "Datenschutz"
        name: "datenschutz"
        delete: false
        file: "content/pages/datenschutz.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - label: "Impressum"
        name: "impressum"
        delete: false
        file: "content/pages/impressum.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - label: "Kontakt"
        name: "contact"
        delete: false
        file: "content/pages/contact.yml"
        fields:
          - {label: Section Name, name: name, widget: string}
          - {label: "Image", name: "image", widget: "image", required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Logo Kontakt, name: image2, widget: image, required: false, tagname: ""}
          - {label: Adresse, name: adress, widget: markdown}

      - label: "About Yella"
        name: "about"
        delete: false
        file: "content/pages/about.yml"
        fields:
          - {label: Section Name, name: name, widget: string}
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Profile Image, name: profileimage, widget: image, required: false, tagname: ""}
          - {label: Section Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Hero Title, name: herotitle, widget: markdown, required: false}


      - label: "Erfahrung"
        name: "erfahrung"
        delete: false
        file: "content/pages/erfahrung.yml"
        fields:
          - {label: Section Name, name: name, widget: string}
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Section Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Hero Title, name: herotitle, widget: markdown, required: false}


      - label: "Leistung"
        name: "services"
        delete: false
        file: "content/pages/services.yml"
        fields:
          - {label: Section Name, name: name, widget: string}
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Section Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Hero Title, name: herotitle, widget: markdown, required: false}

      - label: "Prozess"
        name: "prozess"
        delete: false
        file: "content/pages/process.yml"
        fields:
          - {label: Section Name, name: name, widget: string}
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Section Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Hero Title, name: herotitle, widget: markdown, required: false}

      - label: "Intro Page"
        name: "intro"
        delete: false
        file: "content/pages/intro.yml"
        fields:
          - {label: Section Name, name: name, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Section Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Hero Title, name: herotitle, widget: markdown, required: false}
          - {label: Hero Text, name: herotext, widget: text, required: false}

