name: Leistung
image: /uploads/header03_leistung_venohr_consulting.jpg
title: 'Näher an Mensch und Unternehmen:  Mit Cultural Profiling.'
body: >-
  Im Executive Search geht es um mehr als nur um die Vermittlung von
  potenziellen Profilen: Unternehmenskultur, Mitarbeiter und Persönlichkeit
  eines Kandidaten müssen im Einklang stehen, um die richtige
  Personalentscheidung zu treffen. Zum Cultural Profiling gehört, Haltung und
  Selbstverständnis eines Unternehmens zu verinnerlichen, um die ideal geeignete
  Führungskraft zu identifizieren. Hierfür tauche ich in der Regel für einen Tag
  in Ihr Unternehmen ein, um Identität, Ziele und Ansprüche zu durchdringen.


  Cultural Profiling verschafft Ihnen wertvolle Impulse durch ein intensives und
  unabhängiges Sparring, in dem es allein um die Anforderungen Ihres
  Unternehmens geht. Transparent. Verbindlich. Effizient.
herotitle: ''
